services:
  # Python service
  app:
    build: . # Uses Dockerfile in the current dir
    volumes:
      - .:/app # Sync local code to container (live reload)
    ports:
      - "5000:5000" # Host:Container port
    depends_on:
      - mongodb # Start MongoDB first

  # MongoDB service
  mongodb:
    image: mongo:latest # Official MongoDB image
    volumes:
      - mongodb_data:/data/db # Persist data
    ports:
      - "27017:27017" # MongoDB default port

# Named volume (for persistent DB storage)
volumes:
  mongodb_data:
